openapi: 3.1.0
info:
  title: Microsoft Graph Mail API (App Access)
  version: 1.0.0
  description: Read user mail using Microsoft Graph with app-only access.

servers:
  - url: https://graph.microsoft.com/v1.0

paths:
  /users/{userId}/messages:
    get:
      operationId: getUserMessages
      summary: Get mail messages for a user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      security:
        - oauth2: [https://graph.microsoft.com/.default]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        subject:
                          type: string

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://login.microsoftonline.com/79aa8f1a-1199-4fae-8ed8-2a77d40d6b9d/oauth2/v2.0/token
          scopes:
            https://graph.microsoft.com/.default: App access to Microsoft Graph
